### ISSUE TITLE
Crash on world creating screen + one question

### ISSUE THREAD

**Issue by TheKuwagata** [Darsenia/woodlands#5]
I click on the world creation button and the game crashes with this text: The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalStateException: Failed to load registries due to above errors

[crash-2024-12-06_03.13.19-client.txt](https://github.com/user-attachments/files/18029076/crash-2024-12-06_03.13.19-client.txt)

And question: I tried mod with ht's treechop mod on minecraft version 1.20 and it doesn't work with your trees. An chances for compat with ht's treechop?

**Comment by Darsenia** [comment]
For the crash: could you please add the "latest" log file? Such crashes happen when there is something very obviously bad with a datapack, but it works absolutely fine for me. I'm on the 21.1.76 neoforge. But the whole "mod" itself is a datapack wrapped as a .jar mod, and the only thing for neoforge is the text manifest file, so... No thoughts right now

For the trees: most of the trees are made from "wood",sometimes stripped wood, not logs. Like "oak_wood" instead of "oak_log". And leaves are all "persistent". The trees are also bigger. So in the mod config some values should be changed to allow chop those blocks. Back in the days  with good old Treecapitator and others  these things were easily configured to chop custom handmade trees. No other compatibility is possible for a datapack, just adjusting the configs of a chopper mod.
I'll test different kinds of "choppers" later to figure it out better.

**Comment by TheKuwagata** [comment]
[latest.log](https://github.com/user-attachments/files/18049206/latest.log)

**Comment by Darsenia** [comment]
Ok, I got it.That's an error, I can easily remove it, but I still don't get why I hadn't got this crash with the same .jar, considering the fact that it's a crucial error, the world should not be even created. Very very strange)
If you want an easy quick fix without waiting for the oficial upload, you can remove the file "warped_roots_patch.json" from the data\woodlands\worldgen\placed_feature\flowers inside the .jar file (open with 7.zip or smth else)

**Comment by Darsenia** [comment]
I uploaded the FIX file to the curseforge, it would be available after moderation.Thank you for the bug report!

**Comment by TheKuwagata** [comment]
Big thanks! Love <3
